# Generated by Django 4.2.29 on 2026-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_encounter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
