# Generated by Django 5.2.17 on 2026-09-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_historicalorder_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderresult',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='analyte',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='reference_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='units',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='value',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='analyte',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='reference_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='units',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='value',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
