# Generated by Django 5.2.17 on 2026-09-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_careplan_historicalcareplan_historicalinpatientorder_and_more'),
        ('orders', '0005_historicalorderresult_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderresult',
            name='catalog_analyte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.labanalyte'),
        ),
        migrations.AddField(
            model_name='historicalorderresult',
            name='specimen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.specimen'),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='catalog_analyte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.labanalyte'),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.specimen'),
        ),
    ]
