# Generated by Django 5.2.17 on 2026-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_store_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('nurse', 'Nurse'), ('clinician', 'Clinician'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('cashier', 'Cashier'), ('manager', 'Manager'), ('store', 'Store / inventory'), ('radiology', 'Radiography / imaging operator')], default='reception', max_length=32),
        ),
    ]
