# Generated by Django 5.2.17 on 2026-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False),
        ),
    ]
