# Generated by Django 5.2.17 on 2026-09-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_facilityaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pharmacy', 'Pharmacy only'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('custom', 'Custom services')], max_length=20)),
                ('display_name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('enabled_services', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('configured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuration', to='accounts.facility')),
            ],
        ),
    ]
