# Generated by Django 5.2.17 on 2026-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_facilityconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityconfiguration',
            name='logo',
            field=models.FileField(blank=True, upload_to='private/branding/'),
        ),
        migrations.AddField(
            model_name='facilityconfiguration',
            name='print_footer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='facilityconfiguration',
            name='receipt_paper',
            field=models.CharField(choices=[('a4', 'A4'), ('80mm', 'Thermal 80mm')], default='a4', max_length=16),
        ),
    ]
