# Generated by Django 5.2.17 on 2026-10-01 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_facilityconfiguration_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSupportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(unique=True)),
                ('owner_reference', models.CharField(max_length=160)),
                ('reason', models.CharField(max_length=250)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('origin', models.URLField(unique=True)),
                ('bind_port', models.PositiveIntegerField(unique=True)),
                ('service_type', models.CharField(max_length=20)),
                ('services', models.JSONField(default=list)),
                ('admin_username', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('provisioning', 'Awaiting deployment'), ('active', 'Active'), ('suspended', 'Suspended')], default='provisioning', max_length=20)),
                ('secret_envelope', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
