# Generated by Django 5.2.17 on 2026-10-01 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ownersupportreceipt_tenantdeployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(choices=[('purchase', 'Purchase orders'), ('budget', 'Operating budgets'), ('expense', 'Operating expenses'), ('settlement', 'Expense reconciliation'), ('credit', 'Invoice credits'), ('refund', 'Cash refund authorization'), ('return', 'Medicine returns'), ('price', 'Basket price changes')], max_length=20)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=14)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=250)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_grants', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.facility')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('purchase', 'Purchase orders'), ('budget', 'Operating budgets'), ('expense', 'Operating expenses'), ('settlement', 'Expense reconciliation'), ('credit', 'Invoice credits'), ('refund', 'Cash refund authorization'), ('return', 'Medicine returns'), ('price', 'Basket price changes')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'operation'), name='one_facility_approval_policy')],
            },
        ),
    ]
