# Generated by Django 4.2.29 on 2026-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_historicalpricelistitem_historicalpricelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicconfig',
            name='near_expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='historicalclinicconfig',
            name='near_expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
