# Generated by Django 5.2.17 on 2026-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_clinicconfig_near_expiry_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('insurance', 'Insurance remittance')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('insurance', 'Insurance remittance')], default='cash', max_length=20),
        ),
    ]
