# Generated by Django 4.2.29 on 2026-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_diagnosis_coding_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldiagnosis',
            name='coding_system',
            field=models.CharField(choices=[('ICD10', 'ICD-10'), ('WHO_MOH', 'WHO / MoH coded (e.g. HMIS condition list)'), ('LOCAL', 'Local clinic code')], default='ICD10', help_text='Code list used for HMIS / MoH reporting alignment.', max_length=16),
        ),
    ]
