# Generated by Django 5.2.17 on 2026-09-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodsreceipt_purchaseorder_supplier_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.stocklocation'),
        ),
        migrations.AddField(
            model_name='batch',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.stocklocation'),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
    ]
