# Generated by Django 5.2.17 on 2026-09-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_location_batch_quarantined_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.stocklocation'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.stocklocation'),
        ),
    ]
