# Generated by Django 5.2.17 on 2026-09-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_store_choice'),
        ('inventory', '0005_goodsreceipt_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='facility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.facility'),
        ),
    ]
