# Generated by Django 4.2.29 on 2026-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0003_patient_consent_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='consent_data_processing',
            field=models.BooleanField(default=False, help_text='Patient consents to processing of personal data for care and billing (DPPA-style record).'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='consent_recorded_at',
            field=models.DateTimeField(blank=True, help_text='When consent was last recorded as granted.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='data_retention_until',
            field=models.DateField(blank=True, help_text='Optional policy date after which inactive records may be archived or deleted per clinic SOP.', null=True),
        ),
    ]
