# Generated by Django 5.2.17 on 2026-09-29 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0004_alter_historicalpatient_consent_data_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='allergy_status',
            field=models.CharField(choices=[('unknown', 'Not reviewed'), ('none', 'No known allergies'), ('recorded', 'Allergies recorded')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='medical_record_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy_status',
            field=models.CharField(choices=[('unknown', 'Not reviewed'), ('none', 'No known allergies'), ('recorded', 'Allergies recorded')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
