# Generated by Django 5.2.17 on 2026-09-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0006_unique_patient_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='demographics.patient'),
        ),
    ]
