from django.urls import path
from . import views, advanced_views, offline_views, chart_views, workflow_views, finance_views, workforce_views, management_views, diagnostic_views, visiting_views, engagement_views
urlpatterns = [
    path('suite/appointment-requests/',engagement_views.requests,name='suite-appointment-requests'),
    path('suite/appointment-requests/<int:pk>/',engagement_views.request_review,name='suite-appointment-request-review'),
    path('suite/recalls/',engagement_views.recalls,name='suite-recalls'),
    path('suite/recalls/<int:pk>/action/',engagement_views.recall_action,name='suite-recall-action'),
    path('suite/visiting/',visiting_views.portal,name='visiting-portal'),
    path('suite/visiting/cases/<int:pk>/',visiting_views.case,name='visiting-case'),
    path('suite/visiting-specialists/',visiting_views.manage,name='suite-visiting-manage'),
    path('suite/visiting-specialists/new/<slug:kind>/',visiting_views.create,name='suite-visiting-create'),
    path('suite/visiting-specialists/<int:pk>/revoke/',visiting_views.revoke,name='suite-visiting-revoke'),
    path('suite/diagnostics/',diagnostic_views.board,name='suite-diagnostics'),
    path('suite/diagnostics/templates/',diagnostic_views.templates,name='suite-diagnostic-templates'),
    path('suite/diagnostics/templates/new/',diagnostic_views.template_create,name='suite-diagnostic-template-create'),
    path('suite/diagnostics/templates/<int:pk>/review/',diagnostic_views.template_review,name='suite-diagnostic-template-review'),
    path('suite/diagnostics/orders/<int:pk>/',diagnostic_views.order_detail,name='suite-diagnostic-order'),
    path('suite/diagnostics/orders/<int:pk>/worksheet/<int:template_id>/',diagnostic_views.worksheet,name='suite-diagnostic-worksheet'),
    path('suite/diagnostics/orders/<int:pk>/report/',diagnostic_views.report,name='suite-diagnostic-report'),
    path('suite/diagnostics/sheets/<int:pk>/',diagnostic_views.sheet_detail,name='suite-diagnostic-sheet'),
    path('suite/management/',management_views.home,name='suite-management'),
    path('suite/management/<slug:kind>/',management_views.register,name='suite-management-register'),
    path('suite/management/<slug:kind>/new/',management_views.create,name='suite-management-create'),
    path('suite/management/<slug:kind>/<int:pk>/action/',management_views.action,name='suite-management-action'),
    path('suite/workforce/',workforce_views.board,name='suite-workforce'),
    path('suite/workforce/directory/',workforce_views.directory,name='suite-workforce-directory'),
    path('suite/workforce/inbox/',workforce_views.inbox,name='suite-workforce-inbox'),
    path('suite/workforce/timesheets/',workforce_views.timesheets,name='suite-workforce-timesheets'),
    path('suite/workforce/assign/',workforce_views.assign,name='suite-workforce-assign'),
    path('suite/workforce/new/<slug:kind>/',workforce_views.create,name='suite-workforce-create'),
    path('suite/workforce/new/<slug:kind>/<int:pk>/',workforce_views.create,name='suite-workforce-create-for'),
    path('suite/workforce/shift/<int:pk>/',workforce_views.shift_detail,name='suite-workforce-shift'),
    path('suite/workforce/action/<slug:kind>/<int:pk>/',workforce_views.action,name='suite-workforce-action'),
    path('suite/finance/',finance_views.finance,name='suite-finance'),
    path('suite/finance/invoice/<int:pk>/',finance_views.invoice_detail,name='suite-invoice-detail'),
    path('suite/finance/refunds/<int:pk>/',finance_views.refund_detail,name='suite-refund-detail'),
    path('suite/returns/',finance_views.returns,name='suite-returns'),
    path('suite/returns/<int:pk>/',finance_views.return_detail,name='suite-return-detail'),
    path('suite/price-reviews/',finance_views.price_reviews,name='suite-price-reviews'),
    path('suite/price-reviews/new/<int:line_id>/',finance_views.price_request,name='suite-price-request'),
    path('suite/price-reviews/<int:pk>/',finance_views.price_review,name='suite-price-review'),
    path('suite/replenishment/',finance_views.replenishment,name='suite-replenishment'),
    path('suite/stock/batch/<int:pk>/',finance_views.stock_detail,name='suite-stock-detail'),
    path('suite/visit/<int:pk>/claim/', workflow_views.claim_visit, name='suite-claim-visit'),
    path('suite/department-board/', workflow_views.department_board, name='suite-department-board'),
    path('suite/patient/<int:pk>/handoff/', workflow_views.handoff, name='suite-handoff'),
    path('suite/tasks/new/', workflow_views.task_create, name='suite-task-new'),
    path('suite/tasks/', workflow_views.tasks, name='suite-tasks'),
    path('suite/tasks/<int:pk>/', workflow_views.task_detail, name='suite-task-detail'),
    path('suite/patient/<int:pk>/task/', workflow_views.task_create, name='suite-task-create'),
    path('suite/visit/<int:pk>/note/', workflow_views.note, name='suite-consultation-note'),
    path('suite/note-templates/', workflow_views.templates, name='suite-note-templates'),
    path('suite/patient/<int:pk>/document/', workflow_views.document, name='suite-document-create'),
    path('suite/documents/<int:pk>/download/', workflow_views.document_download, name='suite-document-download'),
    path('suite/lookup/<slug:slug>/<str:field>/', workflow_views.lookup, name='suite-lookup'),
    path('offline/', offline_views.shell, name='suite-offline'),
    path('offline/sw.js', offline_views.service_worker),
    path('offline/api/session/', offline_views.session),
    path('offline/api/patients/', offline_views.patients),
    path('offline/api/devices/', offline_views.devices),
    path('offline/api/prepare/', offline_views.prepare),
    path('offline/api/sync/', offline_views.sync),
    path('suite/specialties/<slug:slug>/<int:pk>/', advanced_views.specialty_detail, name='suite-specialty-detail'),
    path('suite/specialty-follow-up/', advanced_views.specialty_follow_up, name='suite-specialty-follow-up'),
    path('suite/cards/<int:pk>/', advanced_views.identity_card, name='suite-card'),
    path('suite/barcodes/<slug:kind>/<int:pk>/', advanced_views.barcode, name='suite-barcode'),
    path('suite/insurance/prepare/', advanced_views.prepare_insurance, name='suite-prepare-claim'),
    path('suite/claims/<int:pk>/export/', advanced_views.claim_export, name='suite-claim-export'),
    path('suite/collections/<int:pk>/provider/<slug:operation>/', advanced_views.collection_provider, name='suite-provider'),
    path('suite/medication-round/', advanced_views.medication_round, name='suite-medication-round'),
    path('suite/reorder-report/', advanced_views.reorder_report, name='suite-reorder'),
    path('suite/stock/', views.stock_workspace, name='suite-stock'),
    path('suite/find-patient/', chart_views.patient_search, name='suite-patient-search'),
    path('suite/', views.workspace, name='suite-home'),
    path('suite/patient/<int:pk>/', chart_views.patient_chart, name='suite-patient'),
    path('suite/patient/<int:pk>/history/', views.patient_summary, name='suite-patient-history'),
    path('suite/results/<int:pk>/download/', views.result_download, name='suite-download'),
    path('suite/grants/<int:pk>/revoke/', views.revoke_grant, name='suite-revoke'),
    path('suite/<slug:slug>/', views.collection, name='suite-collection'),
    path('suite/<slug:slug>/<int:pk>/<slug:operation>/', views.action, name='suite-action'),
]
