# Generated by Django 5.2.17 on 2026-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_duplicatereview_historicalduplicatereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrefund',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
