# Generated by Django 5.2.17 on 2026-09-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_store_choice'),
        ('operations', '0003_historicalrefund_approved_at_refund_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'name'), name='unique_service_room')],
            },
        ),
    ]
