# Generated by Django 5.2.17 on 2026-09-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_careplan_historicalcareplan_historicalinpatientorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window_start', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='dispatching', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
