# Generated by Django 5.2.17 on 2026-09-30 07:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_historicalvaccination_source_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVaccinationAdverseEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('occurred_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('seriousness', models.CharField(choices=[('undetermined', 'Undetermined'), ('non_serious', 'Non-serious'), ('serious', 'Serious')], default='undetermined', help_text='Staff assessment; this record does not establish causality.', max_length=20)),
                ('action_taken', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('reporting_reference', models.CharField(blank=True, help_text='External reporting reference, if reported. Saving does not submit a report.', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Awaiting review'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=16)),
                ('assessment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.vaccination')),
            ],
            options={
                'verbose_name': 'historical vaccination adverse event',
                'verbose_name_plural': 'historical vaccination adverse events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VaccinationAdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('seriousness', models.CharField(choices=[('undetermined', 'Undetermined'), ('non_serious', 'Non-serious'), ('serious', 'Serious')], default='undetermined', help_text='Staff assessment; this record does not establish causality.', max_length=20)),
                ('action_taken', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('reporting_reference', models.CharField(blank=True, help_text='External reporting reference, if reported. Saving does not submit a report.', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Awaiting review'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=16)),
                ('assessment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverse_events', to='operations.vaccination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
