# Generated by Django 5.2.17 on 2026-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_historicalofflinedevice_offlinedevice_offlinereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinereceipt',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
