# Generated by Django 5.2.17 on 2026-09-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_store_choice'),
        ('demographics', '0007_historicalpatient_merged_into_patient_merged_into'),
        ('operations', '0013_consultationnote_historicalnotetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworktask',
            name='facility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='historicalworktask',
            name='source_kind',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='historicalworktask',
            name='source_pk',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktask',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='source_kind',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='worktask',
            name='source_pk',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='demographics.patient'),
        ),
    ]
