# Generated by Django 5.2.17 on 2026-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_diagnostictemplate_diagnosticworkitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticworksheet',
            name='review_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworksheet',
            name='review_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
