# Generated by Django 5.2.17 on 2026-09-30 20:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


import importlib
canonical=importlib.import_module('apps.operations.migrations.0015_canonical_patient_guards')


def remove_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)


def install_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)
    canonical.install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_room'),
        ('operations', '0031_import_canonical_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_guards,install_guards),
        migrations.AddField(
            model_name='appointmentrequest',
            name='kind',
            field=models.CharField(choices=[('new', 'New booking'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel booking')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='target_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='target_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointmentrequest',
            name='kind',
            field=models.CharField(choices=[('new', 'New booking'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel booking')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalappointmentrequest',
            name='target_appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='historicalappointmentrequest',
            name='target_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmanagementcase',
            name='source_grant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.portalgrant'),
        ),
        migrations.AddField(
            model_name='historicalmanagementcase',
            name='submission_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalportalrecipient',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='An empty list preserves historical summary access. New links use explicit scopes.'),
        ),
        migrations.AddField(
            model_name='managementcase',
            name='source_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='operations.portalgrant'),
        ),
        migrations.AddField(
            model_name='managementcase',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portalrecipient',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='An empty list preserves historical summary access. New links use explicit scopes.'),
        ),
        migrations.CreateModel(
            name='HistoricalExpenseSettlement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('request_key', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('petty_cash', 'Separate petty-cash account')], max_length=20)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_reference', models.CharField(max_length=120)),
                ('evidence', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting reconciliation'), ('confirmed', 'Reconciled'), ('rejected', 'Rejected evidence')], default='pending', max_length=12)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.operatingexpense')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense settlement',
                'verbose_name_plural': 'historical expense settlements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('petty_cash', 'Separate petty-cash account')], max_length=20)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_reference', models.CharField(max_length=120)),
                ('evidence', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting reconciliation'), ('confirmed', 'Reconciled'), ('rejected', 'Rejected evidence')], default='pending', max_length=12)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='operations.operatingexpense')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_expense_settlement')],
            },
        ),
        migrations.RunPython(install_guards,remove_guards),
    ]
