# Generated by Django 5.2.17 on 2026-09-30 20:11

import django.db.models.deletion
from django.db import migrations, models


import importlib
canonical=importlib.import_module('apps.operations.migrations.0015_canonical_patient_guards')


def remove_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)


def install_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)
    canonical.install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_workflow_canonical_guards'),
    ]

    operations = [
        migrations.RunPython(remove_guards,install_guards),
        migrations.AddField(
            model_name='historicalshiftcover',
            name='swap_partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.shiftcover'),
        ),
        migrations.AddField(
            model_name='shiftcover',
            name='swap_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paired_from', to='operations.shiftcover'),
        ),
        migrations.RunPython(install_guards,remove_guards),
    ]
