# Generated by Django 5.2.17 on 2026-09-30 20:17

import django.db.models.deletion
from django.db import migrations, models


import importlib
canonical=importlib.import_module('apps.operations.migrations.0015_canonical_patient_guards')


def remove_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)


def install_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)
    canonical.install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_historicalshiftcover_swap_partner_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_guards,install_guards),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.facilityasset'),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.serviceroom'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.facilityasset'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.serviceroom'),
        ),
        migrations.RunPython(install_guards,remove_guards),
    ]
