# Generated by Django 5.2.17 on 2026-09-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


import importlib
canonical=importlib.import_module('apps.operations.migrations.0015_canonical_patient_guards')


def remove_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)


def install_guards(apps,schema_editor):
    canonical.uninstall(apps,schema_editor)
    canonical.install(apps,schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_diagnosticworkitem_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_guards,install_guards),
        migrations.AddField(
            model_name='diagnostictemplate',
            name='instruction_language',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='diagnostictemplate',
            name='instruction_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='diagnostictemplate',
            name='patient_instructions',
            field=models.TextField(blank=True, help_text='Facility-approved patient preparation instructions; never generated automatically.'),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='instruction_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.diagnostictemplate'),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='instructions_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='instructions_acknowledged_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.portalgrant'),
        ),
        migrations.AddField(
            model_name='diagnosticworkitem',
            name='instructions_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicaldiagnostictemplate',
            name='instruction_language',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicaldiagnostictemplate',
            name='instruction_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='historicaldiagnostictemplate',
            name='patient_instructions',
            field=models.TextField(blank=True, help_text='Facility-approved patient preparation instructions; never generated automatically.'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='instruction_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.diagnostictemplate'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='instructions_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='instructions_acknowledged_grant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.portalgrant'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosticworkitem',
            name='instructions_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceroom',
            name='directions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='managementcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(install_guards,remove_guards),
    ]
