# Generated by Django 5.2.17 on 2026-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_reservation_canonical_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrefundauthorization',
            name='authorized_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalrefundauthorization',
            name='payment_reference',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='refundauthorization',
            name='authorized_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='refundauthorization',
            name='payment_reference',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
