# Generated by Django 4.2.29 on 2026-03-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodsreceipt_purchaseorder_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demographics', '0001_initial'),
        ('pharmacy', '0002_prescription_prescriptionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='historicaldispense',
            name='batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.batch'),
        ),
        migrations.CreateModel(
            name='HistoricalBackorder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='demographics.patient')),
                ('prescription_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharmacy.prescriptionitem')),
            ],
            options={
                'verbose_name': 'historical backorder',
                'verbose_name_plural': 'historical backorders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics.patient')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='pharmacy.prescriptionitem')),
            ],
        ),
    ]
