# Generated by Django 5.2.17 on 2026-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_duration_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
