# Generated by Django 5.2.17 on 2026-09-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_type'),
        ('operations', '0004_serviceroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.serviceroom'),
        ),
    ]
